GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "first blog",
  "author": "dato",
  "url": "http://localhost:3003/api/blogs",
  "likes": "232"
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "bela1",
  "name": "lela",
  "password": "123333"
}
