GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "blog",
  "author": "jama",
  "url": "http://localhost:3003/api/blog",
  "likes": "32"
}
